### ISSUE TITLE
so problem

### ISSUE THREAD

**Issue by manofring** [Corsinvest/cv4pve-pepper#1]
hi
my english is bad, sorry
after downloading, unziping and starting
i get error
Cannot find guest domain /tmp/tmpJYBd7G.vv
./cv4pve-pepper --host=10.192.10.132:8006 --username=root@pam --password=password --vmid=100 --viewer=/usr/bin/virt-viewer
How fix ?
Thx advice

**Comment by franklupo** [comment]
Run with --debug parameter and send me log

**Comment by franklupo** [comment]
Hi,
the services on Proxmox VE are runnning?

**Comment by manofring** [comment]
Method: POST, Url: https://10.192.10.132:8006/api2/json/access/ticket
Parameters:
password : password
username : root
realm : pam
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": {
    "CSRFPreventionToken": "5E432477:7QnjJqfhdaRTRO7n8bfTbJZMOB0",
    "cap": {
      "access": {
        "User.Modify": 1,
        "Group.Allocate": 1,
        "Permissions.Modify": 1
      },
      "storage": {
        "Datastore.AllocateSpace": 1,
        "Permissions.Modify": 1,
        "Datastore.Audit": 1,
        "Datastore.AllocateTemplate": 1,
        "Datastore.Allocate": 1
      },
      "vms": {
        "VM.PowerMgmt": 1,
        "VM.Config.CDROM": 1,
        "Permissions.Modify": 1,
        "VM.Snapshot.Rollback": 1,
        "VM.Audit": 1,
        "VM.Config.HWType": 1,
        "VM.Config.Disk": 1,
        "VM.Clone": 1,
        "VM.Monitor": 1,
        "VM.Config.Network": 1,
        "VM.Backup": 1,
        "VM.Config.CPU": 1,
        "VM.Console": 1,
        "VM.Config.Options": 1,
        "VM.Config.Memory": 1,
        "VM.Migrate": 1,
        "VM.Allocate": 1,
        "VM.Snapshot": 1
      },
      "nodes": {
        "Sys.Modify": 1,
        "Sys.Console": 1,
        "Sys.Audit": 1,
        "Sys.PowerMgmt": 1,
        "Permissions.Modify": 1,
        "Sys.Syslog": 1
      },
      "dc": {
        "Sys.Audit": 1
      }
    },
    "ticket": "PVE:root@pam:5E432477::ZyP51cbO0ZSAxn4RR81hIDyIQGUMSVtImNkz/7ANVskNkUZgfghN+40JX1wfN48dEWheKyssg2ah74gK/T0E9UKiXOmIButpq4w6WVE8xa27KAQidkPWqEPZO9e9ptGSbsdN8c06nZ6ghNCnVprb7df/s84HhcFu5PTqMrdNE/Wk7g4XM6uTJdDYPyC+SyoFwaCiJufAZDHJ65gAGLtZxcV57basZ5+UB4XNMdNxuM1uFE35sLr0ek9US5GEhNRgp9o6YUUa46qzTAt71SoIGPRF+4nvWRD7HljXrWjZ1R+fxgIGeHI6MndDibnzF2Dni6w8S8HJQIf/AfMRDHOcBQ==",
    "username": "root@pam"
  }
}
=============================
Method: GET, Url: https://10.192.10.132:8006/api2/json/cluster/resources?type=vm
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": [
    {
      "name": "dhcp-branch-001",
      "template": 0,
      "disk": 0,
      "netout": 66193182027,
      "mem": 1829228544,
      "vmid": 101,
      "node": "hv-branch-008",
      "type": "qemu",
      "maxcpu": 4,
      "maxdisk": 34359738368,
      "diskread": 177785554432,
      "diskwrite": 195533969408,
      "netin": 21256996292,
      "status": "running",
      "uptime": 1847356,
      "id": "qemu/101",
      "maxmem": 4294967296,
      "cpu": 0.0810046181917339
    },
    {
      "status": "running",
      "uptime": 489565,
      "id": "qemu/407",
      "maxmem": 10737418240,
      "cpu": 0.0135418054727823,
      "name": "server-407",
      "template": 0,
      "disk": 0,
      "netout": 16526,
      "vmid": 407,
      "mem": 6547017728,
      "node": "hv-branch-008",
      "type": "qemu",
      "maxcpu": 8,
      "maxdisk": 107374182400,
      "diskread": 2122910208,
      "diskwrite": 2861752832,
      "netin": 4481406963
    },
    {
      "status": "stopped",
      "uptime": 0,
      "id": "qemu/4071",
      "maxmem": 10737418240,
      "cpu": 0,
      "name": "server-407",
      "template": 0,
      "disk": 0,
      "netout": 0,
      "vmid": 4071,
      "mem": 0,
      "type": "qemu",
      "node": "hv-branch-008",
      "maxdisk": 107374182400,
      "maxcpu": 8,
      "diskread": 0,
      "diskwrite": 0,
      "netin": 0
    }
  ]
}
=============================
Method: POST, Url: https://10.192.10.132:8006/api2/json/nodes/hv-branch-008/qemu/407/spiceproxy
Parameters:
proxy : 10.192.10.132
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": {
    "host-subject": "OU=PVE Cluster Node,O=Proxmox Virtual Environment,CN=hv-branch-008.branch.acme.com",
    "release-cursor": "Ctrl+Alt+R",
    "password": "27f37f368890533ea2b4fbfc655897ab48d8220b",
    "ca": "-----BEGIN CERTIFICATE-----\\nMIIFwjCCA6qgAwIBAgIJANrMU0VtZ8U9MA0GCSqGSIb3DQEBCwUAMHYxJDAiBgNV\\nBAMMG1Byb3htb3ggVmlydHVhbCBFbnZpcm9ubWVudDEtMCsGA1UECwwkMjkwMzIz\\nNmEtYjA2OS00NzA1LTg0OTUtODU5MmU2NmE4NzA0MR8wHQYDVQQKDBZQVkUgQ2x1\\nc3RlciBNYW5hZ2VyIENBMB4XDTE4MDUwMjA4Mzk1MloXDTI4MDQyOTA4Mzk1Mlow\\ndjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYDVQQL\\nDCQyOTAzMjM2YS1iMDY5LTQ3MDUtODQ5NS04NTkyZTY2YTg3MDQxHzAdBgNVBAoM\\nFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw\\nggIKAoICAQDBvdvNOckpC187q2XakveTL7C3E3oavtOE0Zz7yd8RAWt0s0OiN6AM\\njR1/D4LJGAABuz5y/LMtrBYYdzM6w3Kp347OtMgu21m96fnTEfhudUBdnP+zY2To\\nNLB2irdlNycBRUCmm9Wq+YkWkSlDBrKVs/hE5erPi25QanBTRaxk9si/oAn+K7+w\\nExvOsnOhujUlbzoNaU9hGa9qmnUo8e9JbJRqFOMQM5BfHrcYP8td7ATivLEE1ruk\\nKUSACxxVkOUOTwjXsiHj4pW6cMX1UkZs8hA/omRiIw9fn7+lGZHlO1z0J6JpFG7U\\nUhhb+169rq8qMdIUqTOZhYBvMh7fmkF8hIhjbscHxBeWAvIkkmjUAKS1v1UIMYaK\\nbIWL22R0uvSLzsKYd2RKtSfhkFqc3Z6WgA3I1VT3srJMug7ASxLBGkBC5apM4Muz\\nq0XSTkp+2S7jQnxxMepQu9N7PYIZ6OaIHKmSj92VsF/+TOfR9YUrEy8pPhwFHKQK\\nZjx+orILuf2rLXXaGQBrZ7f9NGcKo00NPISpJM8CohffRNPE9LxwOMIL29+wZRHg\\nHzNLNoFeAJg7sQ6w0HOKGp2bnxiFLpPI7FXuMT6mYtC8n+n4YOCdm5PFUKShNrgu\\nDButCnCyOKoKj+3xMXfJVoSLPGayQwqRTohlvlHAlcL6MUpHRCebSwIDAQABo1Mw\\nUTAdBgNVHQ4EFgQUaw9W9njh2RsKa/YF/vKQQGs15q8wHwYDVR0jBBgwFoAUaw9W\\n9njh2RsKa/YF/vKQQGs15q8wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsF\\nAAOCAgEAtkhsjIoppTf0KOFufwgH8eQWbmBUFbov/PmPkB5Gz50o6a9MDlMHl5Wv\\nMGXuXI/yCpJV6VK11tcBOKz+VB7pZ3tQYSqz1vh7LPiUL/XoKdrlL6qz7kdZ9ZD7\\nmU0STQvAiLy6YkZ/UPRIDKJBVG7ZGdRK7EWw59ollfdlGVzs8ywKLRFDh5Pe2FmI\\nqmPrwEySdeU12uaxcAElEgMM+pf69q5KPjaeHinw8tNo22WFLW3ybVdOplTuk6Sr\\nuoQ4ody4AwiTnE++iyQLBIiSZGhU5Tk9+iswJGcH6i+ebli80EZXv4HUYrKSrVdL\\nFUvbqWxd02nYnDVPqsqRrSU93reHhcCwPe5MhLjlUV4VMRIlhL51qhQHzoPQPYhH\\naMYufIkVDjWsa8B6/OpjI58ldYxtP88QKG4J+T93ujWggMr8cSKxXTd7R/k1P8N3\\nww+XIJ4IgfuVF1nCUOKZSg+04hN++YITcTZAxTLPOKl0kUK4Ms6tldkBcKXUrhnM\\nOLZS5B+wVud/bZkE+vns7Hob6zXX5nBLSkInuF9qsNzbsBKK09GKJI2PJvSo567g\\nia7rlUGpzt1P1ArYmi1toumZsKUqqDo/Z+JZivKak1WArXpNWlBpEmdE4zekHbf/\\nL6LjMtQtqzlaM8wZGHhKIe7zHsd5/nyP2rH8T4NRlCdD8I41HXI=\\n-----END CERTIFICATE-----\\n",
    "type": "spice",
    "host": "pvespiceproxy:5e432478:407:hv-branch-008::18b829f4415929f5794277c2d6c1fdb25c7eca66",
    "toggle-fullscreen": "Shift+F11",
    "delete-this-file": 1,
    "secure-attention": "Ctrl+Alt+Ins",
    "title": "VM 407 - server-407",
    "tls-port": 61000,
    "proxy": "http://10.192.10.132:3128"
  }
}
=============================
Run command: "/usr/bin/virt-viewer" "/tmp/tmpHR5CUs.vv"

**Comment by manofring** [comment]
Method: POST, Url: https://10.192.10.132:8006/api2/json/access/ticket
Parameters:
password : password
username : root
realm : pam
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": {
    "CSRFPreventionToken": "5E432477:7QnjJqfhdaRTRO7n8bfTbJZMOB0",
    "cap": {
      "access": {
        "User.Modify": 1,
        "Group.Allocate": 1,
        "Permissions.Modify": 1
      },
      "storage": {
        "Datastore.AllocateSpace": 1,
        "Permissions.Modify": 1,
        "Datastore.Audit": 1,
        "Datastore.AllocateTemplate": 1,
        "Datastore.Allocate": 1
      },
      "vms": {
        "VM.PowerMgmt": 1,
        "VM.Config.CDROM": 1,
        "Permissions.Modify": 1,
        "VM.Snapshot.Rollback": 1,
        "VM.Audit": 1,
        "VM.Config.HWType": 1,
        "VM.Config.Disk": 1,
        "VM.Clone": 1,
        "VM.Monitor": 1,
        "VM.Config.Network": 1,
        "VM.Backup": 1,
        "VM.Config.CPU": 1,
        "VM.Console": 1,
        "VM.Config.Options": 1,
        "VM.Config.Memory": 1,
        "VM.Migrate": 1,
        "VM.Allocate": 1,
        "VM.Snapshot": 1
      },
      "nodes": {
        "Sys.Modify": 1,
        "Sys.Console": 1,
        "Sys.Audit": 1,
        "Sys.PowerMgmt": 1,
        "Permissions.Modify": 1,
        "Sys.Syslog": 1
      },
      "dc": {
        "Sys.Audit": 1
      }
    },
    "ticket": "PVE:root@pam:5E432477::ZyP51cbO0ZSAxn4RR81hIDyIQGUMSVtImNkz/7ANVskNkUZgfghN+40JX1wfN48dEWheKyssg2ah74gK/T0E9UKiXOmIButpq4w6WVE8xa27KAQidkPWqEPZO9e9ptGSbsdN8c06nZ6ghNCnVprb7df/s84HhcFu5PTqMrdNE/Wk7g4XM6uTJdDYPyC+SyoFwaCiJufAZDHJ65gAGLtZxcV57basZ5+UB4XNMdNxuM1uFE35sLr0ek9US5GEhNRgp9o6YUUa46qzTAt71SoIGPRF+4nvWRD7HljXrWjZ1R+fxgIGeHI6MndDibnzF2Dni6w8S8HJQIf/AfMRDHOcBQ==",
    "username": "root@pam"
  }
}
=============================
Method: GET, Url: https://10.192.10.132:8006/api2/json/cluster/resources?type=vm
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": [
    {
      "name": "dhcp-branch-001",
      "template": 0,
      "disk": 0,
      "netout": 66193182027,
      "mem": 1829228544,
      "vmid": 101,
      "node": "hv-branch-008",
      "type": "qemu",
      "maxcpu": 4,
      "maxdisk": 34359738368,
      "diskread": 177785554432,
      "diskwrite": 195533969408,
      "netin": 21256996292,
      "status": "running",
      "uptime": 1847356,
      "id": "qemu/101",
      "maxmem": 4294967296,
      "cpu": 0.0810046181917339
    },
    {
      "status": "running",
      "uptime": 489565,
      "id": "qemu/407",
      "maxmem": 10737418240,
      "cpu": 0.0135418054727823,
      "name": "server-407",
      "template": 0,
      "disk": 0,
      "netout": 16526,
      "vmid": 407,
      "mem": 6547017728,
      "node": "hv-branch-008",
      "type": "qemu",
      "maxcpu": 8,
      "maxdisk": 107374182400,
      "diskread": 2122910208,
      "diskwrite": 2861752832,
      "netin": 4481406963
    },
    {
      "status": "stopped",
      "uptime": 0,
      "id": "qemu/4071",
      "maxmem": 10737418240,
      "cpu": 0,
      "name": "server-407",
      "template": 0,
      "disk": 0,
      "netout": 0,
      "vmid": 4071,
      "mem": 0,
      "type": "qemu",
      "node": "hv-branch-008",
      "maxdisk": 107374182400,
      "maxcpu": 8,
      "diskread": 0,
      "diskwrite": 0,
      "netin": 0
    }
  ]
}
=============================
Method: POST, Url: https://10.192.10.132:8006/api2/json/nodes/hv-branch-008/qemu/407/spiceproxy
Parameters:
proxy : 10.192.10.132
StatusCode:          OK
ReasonPhrase:        OK
IsSuccessStatusCode: True
{
  "data": {
    "host-subject": "OU=PVE Cluster Node,O=Proxmox Virtual Environment,CN=hv-branch-008.branch.acme.com",
    "release-cursor": "Ctrl+Alt+R",
    "password": "27f37f368890533ea2b4fbfc655897ab48d8220b",
    "ca": "-----BEGIN CERTIFICATE-----\\nMIIFwjCCA6qgAwIBAgIJANrMU0VtZ8U9MA0GCSqGSIb3DQEBCwUAMHYxJDAiBgNV\\nBAMMG1Byb3htb3ggVmlydHVhbCBFbnZpcm9ubWVudDEtMCsGA1UECwwkMjkwMzIz\\nNmEtYjA2OS00NzA1LTg0OTUtODU5MmU2NmE4NzA0MR8wHQYDVQQKDBZQVkUgQ2x1\\nc3RlciBNYW5hZ2VyIENBMB4XDTE4MDUwMjA4Mzk1MloXDTI4MDQyOTA4Mzk1Mlow\\ndjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYDVQQL\\nDCQyOTAzMjM2YS1iMDY5LTQ3MDUtODQ5NS04NTkyZTY2YTg3MDQxHzAdBgNVBAoM\\nFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw\\nggIKAoICAQDBvdvNOckpC187q2XakveTL7C3E3oavtOE0Zz7yd8RAWt0s0OiN6AM\\njR1/D4LJGAABuz5y/LMtrBYYdzM6w3Kp347OtMgu21m96fnTEfhudUBdnP+zY2To\\nNLB2irdlNycBRUCmm9Wq+YkWkSlDBrKVs/hE5erPi25QanBTRaxk9si/oAn+K7+w\\nExvOsnOhujUlbzoNaU9hGa9qmnUo8e9JbJRqFOMQM5BfHrcYP8td7ATivLEE1ruk\\nKUSACxxVkOUOTwjXsiHj4pW6cMX1UkZs8hA/omRiIw9fn7+lGZHlO1z0J6JpFG7U\\nUhhb+169rq8qMdIUqTOZhYBvMh7fmkF8hIhjbscHxBeWAvIkkmjUAKS1v1UIMYaK\\nbIWL22R0uvSLzsKYd2RKtSfhkFqc3Z6WgA3I1VT3srJMug7ASxLBGkBC5apM4Muz\\nq0XSTkp+2S7jQnxxMepQu9N7PYIZ6OaIHKmSj92VsF/+TOfR9YUrEy8pPhwFHKQK\\nZjx+orILuf2rLXXaGQBrZ7f9NGcKo00NPISpJM8CohffRNPE9LxwOMIL29+wZRHg\\nHzNLNoFeAJg7sQ6w0HOKGp2bnxiFLpPI7FXuMT6mYtC8n+n4YOCdm5PFUKShNrgu\\nDButCnCyOKoKj+3xMXfJVoSLPGayQwqRTohlvlHAlcL6MUpHRCebSwIDAQABo1Mw\\nUTAdBgNVHQ4EFgQUaw9W9njh2RsKa/YF/vKQQGs15q8wHwYDVR0jBBgwFoAUaw9W\\n9njh2RsKa/YF/vKQQGs15q8wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsF\\nAAOCAgEAtkhsjIoppTf0KOFufwgH8eQWbmBUFbov/PmPkB5Gz50o6a9MDlMHl5Wv\\nMGXuXI/yCpJV6VK11tcBOKz+VB7pZ3tQYSqz1vh7LPiUL/XoKdrlL6qz7kdZ9ZD7\\nmU0STQvAiLy6YkZ/UPRIDKJBVG7ZGdRK7EWw59ollfdlGVzs8ywKLRFDh5Pe2FmI\\nqmPrwEySdeU12uaxcAElEgMM+pf69q5KPjaeHinw8tNo22WFLW3ybVdOplTuk6Sr\\nuoQ4ody4AwiTnE++iyQLBIiSZGhU5Tk9+iswJGcH6i+ebli80EZXv4HUYrKSrVdL\\nFUvbqWxd02nYnDVPqsqRrSU93reHhcCwPe5MhLjlUV4VMRIlhL51qhQHzoPQPYhH\\naMYufIkVDjWsa8B6/OpjI58ldYxtP88QKG4J+T93ujWggMr8cSKxXTd7R/k1P8N3\\nww+XIJ4IgfuVF1nCUOKZSg+04hN++YITcTZAxTLPOKl0kUK4Ms6tldkBcKXUrhnM\\nOLZS5B+wVud/bZkE+vns7Hob6zXX5nBLSkInuF9qsNzbsBKK09GKJI2PJvSo567g\\nia7rlUGpzt1P1ArYmi1toumZsKUqqDo/Z+JZivKak1WArXpNWlBpEmdE4zekHbf/\\nL6LjMtQtqzlaM8wZGHhKIe7zHsd5/nyP2rH8T4NRlCdD8I41HXI=\\n-----END CERTIFICATE-----\\n",
    "type": "spice",
    "host": "pvespiceproxy:5e432478:407:hv-branch-008::18b829f4415929f5794277c2d6c1fdb25c7eca66",
    "toggle-fullscreen": "Shift+F11",
    "delete-this-file": 1,
    "secure-attention": "Ctrl+Alt+Ins",
    "title": "VM 407 - server-407",
    "tls-port": 61000,
    "proxy": "http://10.192.10.132:3128"
  }
}
=============================
Run command: "/usr/bin/virt-viewer" "/tmp/tmpHR5CUs.vv"

**Comment by manofring** [comment]
pve-manager/5.4-13/aee6f0ec (running kernel: 4.15.18-20-pve)

**Comment by manofring** [comment]
./cv4pve-pepper started from Ubuntu 16.04 amd64

**Comment by franklupo** [comment]
Try use /usr/bin/remote-viewer

**Comment by manofring** [comment]
started from Win10 powershell
last release 1.1.0 x86_64
.\cv4pve-pepper.exe --host 10.192.10.132 --username "root@pam" --password password --vmid=407  --viewer "C:\Program Files\VirtViewer v8.0-256\bin\remote-viewer.exe" --debug
Method: POST, Url: https://10.192.10.132:8006/api2/json/access/ticket
Parameters:
password : password
username : root
realm : pam
StatusCode:          Forbidden
ReasonPhrase:        Forbidden
IsSuccessStatusCode: False
Problem connection!

**Comment by franklupo** [comment]
The problem as the connection.
Try https://github.com/Corsinvest/cv4pve-cli check connection to Proxmox VE work

**Comment by manofring** [comment]
in win10 x64 work!
im find problem, not work with ip adress, but work with fqdn hostname
how resolve this problem? im use vpn and write strings in /etc/hosts not good idea.
thx for advance

P.S. next will be testing home ubuntu.

**Comment by manofring** [comment]
> 
> 
> The problem as the connection.
> Try https://github.com/Corsinvest/cv4pve-cli check connection to Proxmox VE work

in --debug log im see resolving ipaddress in fqdn hostname... but not work

**Comment by franklupo** [comment]
You are connect in vpn?

**Comment by manofring** [comment]
> You are connect in vpn?

yes, im connect from home ubuntu to work with vpn.
On ubuntu work with ip address only without fqdn hostname
and viewer option must be
--viewer=/usr/bin/remote-viewer
