### ISSUE TITLE
Multipass Ubuntu / Macosx Forwarding

### ISSUE THREAD

**Issue by jimthedj65** [Corsinvest/cv4pve-pepper#13]
Hi Frank,

Thanks for your app, it greatly simplifies my windows spice connections and for that, I thank you.  I was wondering if I could forward this cv4pve-pepper app to Xquartz through ssh -XY etc I have tried it with exporting DISPLAY as a shell and I have tried running the app as a forward ssh session.  Remote Viewer runs ok in XQuartz?

any idea if your cv4pepper will forward through ssh -XY session, it appears to run but I don't get an XQuartz window opening, I have installed firefox and it runs ok.

**Comment by jimthedj65** [comment]
I ran it with a stopped vm, simple error, works great, just need to try and get sound passed through, I resolved by passing the --debug parameter

**Comment by franklupo** [comment]
Please add the result of your tests so that I can update the guide

Best regards

**Comment by jimthedj65** [comment]
> Please add the result of your tests so that I can update the guide
> 
> Best regards

Hi Frank,  I will be delighted to do that, I have rebuilt my mac after a crash and just back tracking my steps, battling with Unable to init server: Could not connect: Connection refused

Once I get a working 18.04 and 20.04 on multipass and its stable I will post it here... thanks for the script its a big help.

**Comment by jimthedj65** [comment]
Mac-OS Big Sur fresh installed and updated.  Multipass Ubuntu 18.04, I will list it all the build in another post, I am hoping I can find time to make a docker build out of it.  It runs really fast from 2000 miles away on a i7 4790 base server.

I managed to get over the init error by resolving some issues in multipass, install X11-org etc so far making progress on the pulseaudio side.

(remote-viewer:1832): dbind-WARNING **: 23:46:47.281: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-VUheRPsSjR: Connection refused

(remote-viewer:1832): GLib-GIO-CRITICAL **: 23:46:47.321: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Home directory not accessible: Permission denied

(remote-viewer:1832): GSpice-WARNING **: 23:46:48.355: PulseAudio context failed Connection refused

(remote-viewer:1832): GSpice-WARNING **: 23:46:48.355: pa_context_connect() failed: Connection refused
Home directory not accessible: Permission denied

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:48.392: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:48.392: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Home directory not accessible: Permission denied

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:48.410: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:48.410: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:49.074: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:49.074: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:49.074: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GSpice-WARNING **: 23:46:49.095: gst lacks volume capabilities on src

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:49.096: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(remote-viewer:1832): GSpice-WARNING **: 23:46:49.096: gst lacks mute capabilities on src: 0

(remote-viewer:1832): GLib-GObject-CRITICAL **: 23:46:49.096: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by franklupo** [comment]
Hi,
this is a problem of permission **Home directory not accessible: Permission denied**

**Comment by jimthedj65** [comment]
> Hi, this is a problem of permission **Home directory not accessible: Permission denied**

H there sorry about the long delay in getting back to you, it was indeed permissions. I got everything working apart from the sound.  Great project, it will take quite a bit of work to work through compression.

**Comment by franklupo** [comment]
Perfect. You are welcome
