### ISSUE TITLE
Pass arguments to remote-viewer.exe from cv4pve-pepper?

### ISSUE THREAD

**Issue by vipergts450** [Corsinvest/cv4pve-pepper#14]
Hi all,

Would it be possible to pass some command line arguments like -f and -z to remote-viewer while calling cv4pve-pepper? I would like to script for starting zoomed and in full-screen for some of my guests, but the remote-viewer line doesn't like having arguments at the end and fails to launch.

**Comment by franklupo** [comment]
Hi,
at this moment it is not possible, I think about it and find a solution

Best regards

**Comment by franklupo** [comment]
Hi,
I added a new option * - viewer-options * send the options directly to the viewer.
It seems like a good solution to me.

What do you think about it?

best regards

**Comment by vipergts450** [comment]
That's exactly how I envisioned it. Should work fine. Tante grazie!

**Comment by TimoteusRuotsalainen** [comment]
I also need this. Sounds good
