### ISSUE TITLE
Support multiple host for HA in --proxy

### ISSUE THREAD

**Issue by expertaz-zz** [Corsinvest/cv4pve-pepper#15]
Hello Frank,
First of  all thank you for this wonderful tool,just tested windows x64 version with parameter --proxy with success. 
I just made 3 node Proxmox 7 HA Ceph cluster for our VDI needs,is it possible add HA multiple host support for parameter --proxy?

or is it needed?what happens when SPICE proxy server is dead?will all remote-viewer clients will drop connection?

Thanks in advance,
Hafiz.

**Comment by franklupo** [comment]
Hi,
I don't know if multiple hosts can be specified. See [Documentation](https://www.spice-space.org/spice-proxy.html)

Best regards
