### ISSUE TITLE
Keep getting "VM/CT ### Not Found"

### ISSUE THREAD

**Issue by tokenwizard** [Corsinvest/cv4pve-pepper#22]
Let me start by saying I had this working. I was running a VM (ID 106) with an install of Linux Lite and the Display set to SPICE. 

I was able to connect to the Spice session from a Raspberry Pi using the command:
`cv4pve-pepper --host=192.168.7.5 --username=vm-viewer@pve --password=<redacted> --vmid 106 --viewer-options "-k -f" --viewer /usr/bin/remote-viewer`

Today I was having no love for Linux Lite and replaced it with Xubuntu (deleted the VM and created a new one, which got assigned the same ID 106). I have it set with the SPICE display as well and I can access it from my desktop by opening the vv file in Remote Viewer. But the above command on the Raspberry Pi just keeps saying that it cannot find the VM:
`Unhandled exception: System.ArgumentException: VM/CT '106' not found!
   at Corsinvest.ProxmoxVE.Api.Extension.ClientExtension.GetVm(PveClient client, String vmIdOrName)
   at Corsinvest.ProxmoxVE.Pepper.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
--- End of stack trace from previous location ---
`
I also get the same error if I try to run the above command from my Desktop. So it seems I can launch it with the temporary vv file. but can no longer launch it using cv4pve-pepper.

**Comment by franklupo** [comment]
Hi,
 you can  run with option --debug and attach log

Best regards

**Comment by franklupo** [comment]
Check permission

**Comment by tokenwizard** [comment]
It was a permissions issue. Apparently I added the wrong user account back to the new VM.

**Comment by tokenwizard** [comment]
See previous comment. In Proxmox, needed to add Permission for the user to access the VM.

**Comment by franklupo** [comment]
You are welcome
