### ISSUE TITLE
GSpice-Critical

### ISSUE THREAD

**Issue by iptvcld** [Corsinvest/cv4pve-pepper#25]
Once in a while i can getting this error when using your tools

![image](https://github.com/Corsinvest/cv4pve-pepper/assets/34818686/a4d668da-ea2b-433e-a795-387b153987aa)

Thanks

**Comment by iptvcld** [comment]
If i close the cmd and try a couple time, then it is ok. Just not sure what I am doing wrong.. As sometimes when I access, there are no errors

**Comment by franklupo** [comment]
HI,
but the program work?

**Comment by iptvcld** [comment]
Program works but the command window stays open with errors keep showing and if you close the cmd then program stops. But sometimes it runs ok with no errors.

**Comment by iptvcld** [comment]
If you know any other way to connect with spice without logging into proxmox GUI, please let me know. I am using Windows for my viewer. Thank you for your help.

**Comment by iptvcld** [comment]
This is a great script that does the same. 

https://forum.proxmox.com/threads/after-searching-for-a-way-to-automagically-connect-to-spice-and-coming-up-empty-handed-ive-created-a-script-for-anyone-with-the-same-issue.82896/

**Comment by franklupo** [comment]
I'm checking to run virt-viewer with no console output
