### ISSUE TITLE
Unable to connect to libvirt with URI: [none]

### ISSUE THREAD

**Issue by Chouffy** [Corsinvest/cv4pve-pepper#26]
Hi,

I have trouble making this work, unfortunately :(
This is my command line call: `cv4pve-pepper.exe --host=HOST.lan --api-token 'cv4pve@pve!spice=uuidhere' --vmid 400 --viewer D:\Apps\Applications\VirtViewer\bin\virt-viewer.exe` (System: Windows 11 23H2 x64"
The call returns nothing (but no error either)

And I get this message box that says "Unable to connect to libvirt with URI: [none]"
![image](https://github.com/Corsinvest/cv4pve-pepper/assets/9288966/aa895348-c3b2-4d03-8ee7-3c8c86cd7200)

I've checked the permission of my`cv4pve` user, and I can open a SPICE console from the web GUI.
I also checked that I assigned an API Token permission specifically to the `400` VM

Any help welcome!

**Comment by franklupo** [comment]
Does it work with user and password?

**Comment by Chouffy** [comment]
I have the same error if I use `--username=xx@pve --password=xx` instead of `--api-token` 😢

**Comment by Chouffy** [comment]
Would it be possible to download the SPICE config file instead of launching the viewer directly?
So we can check if this steps works as expected 🤔

**Comment by franklupo** [comment]
run with --debug. 
one possible problem is the vnc proxy.
use --proxy https:/host:port


best regards

**Comment by Chouffy** [comment]
Thanks @franklupo !
Using `--debug`, I was able to check where the `.vv` file was stored. If I launched it manually, it was working just fine.
So actually it was the `--viewer` parameter that I got wrong: at least on Windows, you have to call `remote-viewer.exe` and not `virt-viewer.exe` … I just saw it in the Readme 🤦
I'll submit a PR to reflect this. Thanks for this nice piece of software, really helpful!
