### ISSUE TITLE
Non-expiring virt-viewer file

### ISSUE THREAD

**Issue by KXRIST** [Corsinvest/cv4pve-pepper#29]
Hi,

I have the same issue as discussed and i am opening an issue here as you suggested some time ago.
https://forum.proxmox.com/threads/virt-viewer-connection-to-proxmox-vms-from-network-clients.91295/

i'd appreciate your help.

Konstantin

**Comment by franklupo** [comment]
the problem is that of the expiring session?

**Comment by KXRIST** [comment]
yes, .vv file it lasts only for some seconds. I d like to have the option to call the connection whenever i want

**Comment by franklupo** [comment]
I don't understand with it doesn't work?

**Comment by KXRIST** [comment]
it doesn’t, i need a file that shall never expire and open it directly from the app. how to create it?

**Comment by franklupo** [comment]
This is not possible. Application starts a new connection with proxmoxm every time.

**Comment by KXRIST** [comment]
sorry i didn’t know that. so, its not as convenient as in vnc where you simply open the session from the client without logging to prox mox.
i thought there was another way….

many thanks

**Comment by franklupo** [comment]
It's not something else.
Each time a file is generated and virt-viewer is started.

best regards
