### ISSUE TITLE
optionally disable cmd/console window

### ISSUE THREAD

**Issue by ndroftheline** [Corsinvest/cv4pve-pepper#3]
Hello,

Thank you for posting this great utility. I found it from the Proxmox forum post you made here: https://forum.proxmox.com/threads/remote-spice-access-without-using-web-manager.16561/page-5

I am using it successfully now, but I was wondering if there is a way of optionally disabling the cmd/console window that launches with the session? 

Thanks again,

~ndr

**Comment by Lobstarr** [comment]
Hello, i would really appreciate it too!

**Comment by franklupo** [comment]
Hi,
we are running tests.

Best regards
