### ISSUE TITLE
Spiceproxy not implemented

### ISSUE THREAD

**Issue by TableCoffee** [Corsinvest/cv4pve-pepper#30]
I recently updated my PVE host to 8.2, and cv4pve-pepper was also updated through the Aur on Arch so I'm not sure which was the actual cause but but running my usual command to launch a session results in the below error. Any help or direction is appreciated. 

```
cv4pve-pepper --host=10.10.20.20 --api-token 'root@pam!pveapi=25349687-dcbe-4d8d-b4d5-a6c3e2a4a3f2' --vmid 102 --viewer /usr/bin/remote-viewer

Error: Method 'POST /nodes/pve/qemu/qemu/102/spiceproxy' not implemented'
```
spiceproxy and pveproxy are both running and starting a spice session via the PVE web admin works without issue.

**Comment by franklupo** [comment]
HI,
can you run with the --debug parameter and attach logs? remove passwords from log.

Best regards

**Comment by Alexey063** [comment]
Hi. May be url is incorrect? >> /nodes/pve/qemu/qemu/102/spiceproxy'
In that URL the word is dublicate 'qemu'. Or is it normaly?

**Comment by franklupo** [comment]
Hi, I found the problem. I will be releasing a new version soon.

best regards
