### ISSUE TITLE
lxc container

### ISSUE THREAD

**Issue by Sniper013220** [Corsinvest/cv4pve-pepper#32]
Does not work with lxc container.
cv4pve-pepper.exe" --host 192.168.10.122:8006 --username root --password ******* --vmid 733 --viewer "C:\Program Files\VirtViewer v11.0-256\bin\remote-viewer.exe"
Returns an error "Configuration file 'nodes/pve/qemu-server/733.conf' does not exist"
lxc container are located in 'nodes/pve/lxc/733.conf'
What am I doing wrong?

**Comment by franklupo** [comment]
Hi,
can you run with --debug parameter and attach log? 
WARNING remove password.

Best reagrds

**Comment by Sniper013220** [comment]
<details>
  <summary>Log</summary>
  cv4pve-pepper.exe" --host 192.168.10.122:8006 --username root --password ******* --vmid 733 --start-or-resume --debug --viewer ### "C:\Program Files\VirtViewer v11.0-256\bin\remote-viewer.exe" --viewer-options -f
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Login: root
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Method: POST, Url: https://192.168.10.122:8006/api2/json/access/ticket
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Parameters:
      password : *******
      username : root
      realm : pam
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      StatusCode:          OK
      ReasonPhrase:        OK
      IsSuccessStatusCode: True
trce: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      {
        "data": {
          "username": "root@pam",
          "ticket": "PVE:root@pam:66628384::AkZn4G+8+i7mzHh4J8Lg1+QD5wzeqDIZHsxQl8rCMkFV6a0cLOyFCDLl2v8DUt00ktEHQjyFqpE7m4hDpLfu9PP/ZhjSSKUPBedc8XNZQ6xaH6thzjL1lz4MkNCQ8E5iEArQGnHzthSzUCfp/7HqfsnfN/6pmzY0ljYGeB3Ol7a2p95DfHeEYE/ccS2fCyliuoO7UuAu4FHwXGgiOfsFEOOIzhJqrwDC4NdHMO76oNT1037iLE25Ou/trZK2yT7YA3LMNo8qVaLeFyhwAKBsf/C5seK8v1YGP6W590xYXSP/SU+qRk69Qr9yuB/LugLmccjyIBSJEidVZeaFfJmVHw==",
          "cap": {
            "access": {
              "Permissions.Modify": 1,
              "User.Modify": 1,
              "Group.Allocate": 1
            },
            "nodes": {
              "Sys.Modify": 1,
              "Sys.Audit": 1,
              "Sys.AccessNetwork": 1,
              "Sys.Console": 1,
              "Sys.PowerMgmt": 1,
              "Sys.Incoming": 1,
              "Sys.Syslog": 1,
              "Permissions.Modify": 1
            },
            "mapping": {
              "Mapping.Audit": 1,
              "Mapping.Modify": 1,
              "Mapping.Use": 1,
              "Permissions.Modify": 1
            },
            "vms": {
              "VM.Config.CPU": 1,
              "VM.Config.Disk": 1,
              "VM.Config.Network": 1,
              "VM.Allocate": 1,
              "VM.Clone": 1,
              "VM.Monitor": 1,
              "VM.Config.CDROM": 1,
              "VM.Audit": 1,
              "VM.Config.Memory": 1,
              "VM.Config.Cloudinit": 1,
              "VM.Config.HWType": 1,
              "VM.Migrate": 1,
              "VM.Config.Options": 1,
              "VM.PowerMgmt": 1,
              "VM.Console": 1,
              "VM.Snapshot": 1,
              "VM.Backup": 1,
              "VM.Snapshot.Rollback": 1,
              "Permissions.Modify": 1
            },
            "storage": {
              "Datastore.Audit": 1,
              "Datastore.AllocateSpace": 1,
              "Permissions.Modify": 1,
              "Datastore.Allocate": 1,
              "Datastore.AllocateTemplate": 1
            },
            "sdn": {
              "SDN.Use": 1,
              "SDN.Audit": 1,
              "SDN.Allocate": 1,
              "Permissions.Modify": 1
            },
            "dc": {
              "Sys.Modify": 1,
              "Sys.Audit": 1,
              "SDN.Use": 1,
              "SDN.Audit": 1,
              "SDN.Allocate": 1
            }
          },
          "CSRFPreventionToken": "66628384:8BTod++twqhhppPr952hCHmtsV4RYoldKdAhtnyP1TY"
        }
      }
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Method: GET, Url: https://192.168.10.122:8006/api2/json/cluster/resources?type=vm
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      StatusCode:          OK
      ReasonPhrase:        OK
      IsSuccessStatusCode: True
trce: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      {
        "data": [
          {
            "uptime": 3638789,
            "name": "serv-omv",
            "template": 0,
            "vmid": 701,
            "status": "running",
            "id": "qemu/701",
            "type": "qemu",
            "cpu": 0.0130649338163364,
            "maxcpu": 3,
            "mem": 2544430500,
            "tags": "nas",
            "diskread": 3593344448046,
            "netin": 638990631203,
            "netout": 2893226226506,
            "diskwrite": 662339924992,
            "maxmem": 4294967296,
            "node": "pve",
            "maxdisk": 21474836480,
            "disk": 0
          },
          {
            "uptime": 3638784,
            "name": "omv",
            "id": "qemu/702",
            "status": "running",
            "vmid": 702,
            "template": 0,
            "cpu": 0.00816558363521025,
            "type": "qemu",
            "tags": "nas",
            "mem": 2635874320,
            "maxcpu": 3,
            "diskread": 15150295644,
            "maxmem": 4294967296,
            "diskwrite": 51637301248,
            "netout": 115270272,
            "netin": 6148551732,
            "disk": 0,
            "maxdisk": 21474836480,
            "node": "pve"
          },
          {
            "maxcpu": 1,
            "mem": 215985695,
            "diskread": 599347864,
            "netin": 5249846947,
            "netout": 13295575,
            "diskwrite": 3667518464,
            "maxmem": 536870912,
            "node": "pve",
            "maxdisk": 5368709120,
            "disk": 0,
            "name": "hasp433",
            "uptime": 3638779,
            "vmid": 726,
            "template": 0,
            "status": "running",
            "id": "qemu/726",
            "type": "qemu",
            "cpu": 0.0264564909780812
          },
          {
            "cpu": 0,
            "type": "lxc",
            "id": "lxc/732",
            "status": "stopped",
            "vmid": 732,
            "template": 0,
            "uptime": 0,
            "name": "psql",
            "disk": 0,
            "maxdisk": 107374182400,
            "node": "pve",
            "maxmem": 8589934592,
            "netout": 0,
            "diskwrite": 0,
            "netin": 0,
            "diskread": 0,
            "mem": 0,
            "maxcpu": 4
          },
          {
            "uptime": 81418,
            "name": "pbx",
            "id": "lxc/733",
            "status": "running",
            "vmid": 733,
            "template": 0,
            "cpu": 0.0026296288129705,
            "type": "lxc",
            "mem": 74940416,
            "maxcpu": 2,
            "diskread": 556969984,
            "maxmem": 2147483648,
            "netout": 4270,
            "diskwrite": 22261760,
            "netin": 120019464,
            "disk": 838225920,
            "maxdisk": 10464022528,
            "node": "pve"
          },
          {
            "uptime": 0,
            "name": "only-ofice",
            "vmid": 734,
            "template": 0,
            "id": "lxc/734",
            "status": "stopped",
            "type": "lxc",
            "cpu": 0,
            "mem": 0,
            "maxcpu": 4,
            "diskread": 0,
            "netin": 0,
            "maxmem": 8589934592,
            "netout": 0,
            "diskwrite": 0,
            "maxdisk": 53687091200,
            "disk": 0,
            "node": "pve"
          },
          {
            "vmid": 735,
            "template": 0,
            "status": "running",
            "id": "lxc/735",
            "type": "lxc",
            "cpu": 0.000545772017786331,
            "name": "tor",
            "uptime": 3638773,
            "netin": 340408335644,
            "netout": 582209013297,
            "diskwrite": 311246548992,
            "maxmem": 2147483648,
            "node": "pve",
            "disk": 1206059008,
            "maxdisk": 8350298112,
            "maxcpu": 2,
            "mem": 303575040,
            "tags": "nas",
            "diskread": 3091057446912
          },
          {
            "uptime": 0,
            "name": "deb12",
            "status": "stopped",
            "id": "qemu/742",
            "vmid": 742,
            "template": 0,
            "cpu": 0,
            "type": "qemu",
            "maxcpu": 4,
            "mem": 0,
            "diskread": 0,
            "netout": 0,
            "diskwrite": 0,
            "maxmem": 8589934592,
            "netin": 0,
            "node": "pve",
            "maxdisk": 53687091200,
            "disk": 0
          },
          {
            "cpu": 0,
            "type": "qemu",
            "id": "qemu/744",
            "status": "stopped",
            "vmid": 744,
            "template": 0,
            "name": "majaro-kde",
            "uptime": 0,
            "disk": 0,
            "maxdisk": 42949672960,
            "node": "pve",
            "maxmem": 8589934592,
            "diskwrite": 0,
            "netout": 0,
            "netin": 0,
            "diskread": 0,
            "mem": 0,
            "maxcpu": 4
          },
          {
            "disk": 0,
            "maxdisk": 34359738368,
            "node": "pve",
            "maxmem": 8589934592,
            "netout": 0,
            "diskwrite": 0,
            "netin": 0,
            "diskread": 0,
            "mem": 0,
            "maxcpu": 4,
            "cpu": 0,
            "type": "qemu",
            "id": "qemu/747",
            "status": "stopped",
            "vmid": 747,
            "template": 0,
            "uptime": 0,
            "name": "mx-kde"
          },
          {
            "diskread": 0,
            "mem": 0,
            "maxcpu": 4,
            "maxdisk": 34359738368,
            "disk": 0,
            "node": "pve",
            "netin": 0,
            "maxmem": 8589934592,
            "diskwrite": 0,
            "netout": 0,
            "name": "web1c-10",
            "uptime": 0,
            "type": "qemu",
            "cpu": 0,
            "vmid": 752,
            "template": 0,
            "id": "qemu/752",
            "status": "stopped"
          },
          {
            "name": "RT-chr-7.14",
            "uptime": 3638771,
            "vmid": 764,
            "template": 0,
            "status": "running",
            "id": "qemu/764",
            "type": "qemu",
            "cpu": 0.0293961010867569,
            "maxcpu": 2,
            "mem": 286036061,
            "diskread": 68585984,
            "netin": 6926793276923,
            "diskwrite": 121266176,
            "netout": 6914566978559,
            "maxmem": 1073741824,
            "node": "pve",
            "disk": 0,
            "maxdisk": 1207959552
          },
          {
            "uptime": 3638765,
            "name": "Bee-chr-7.14",
            "status": "running",
            "id": "qemu/765",
            "vmid": 765,
            "template": 0,
            "cpu": 0.0333155812316578,
            "type": "qemu",
            "maxcpu": 1,
            "mem": 289870191,
            "diskread": 46365696,
            "diskwrite": 24911872,
            "netout": 22294768028,
            "maxmem": 1073741824,
            "netin": 27114525741,
            "node": "pve",
            "disk": 0,
            "maxdisk": 1207959552
          },
          {
            "vmid": 773,
            "template": 0,
            "id": "qemu/773",
            "status": "stopped",
            "type": "qemu",
            "cpu": 0,
            "name": "srv08",
            "uptime": 0,
            "netin": 0,
            "maxmem": 8589934592,
            "netout": 0,
            "diskwrite": 0,
            "disk": 0,
            "maxdisk": 34359738368,
            "node": "pve",
            "mem": 0,
            "maxcpu": 6,
            "diskread": 0
          },
          {
            "diskread": 0,
            "maxcpu": 4,
            "mem": 0,
            "node": "pve",
            "disk": 0,
            "maxdisk": 42949672960,
            "netin": 0,
            "netout": 0,
            "diskwrite": 0,
            "maxmem": 4294967296,
            "name": "w7-ohpk",
            "uptime": 0,
            "type": "qemu",
            "cpu": 0,
            "vmid": 774,
            "template": 0,
            "status": "stopped",
            "id": "qemu/774"
          },
          {
            "diskread": 0,
            "maxcpu": 4,
            "mem": 0,
            "node": "pve",
            "maxdisk": 0,
            "disk": 0,
            "diskwrite": 0,
            "netout": 0,
            "maxmem": 4294967296,
            "netin": 0,
            "name": "w10-2024-05-legace",
            "uptime": 0,
            "cpu": 0,
            "type": "qemu",
            "status": "stopped",
            "id": "qemu/775",
            "vmid": 775,
            "template": 0
          },
          {
            "uptime": 0,
            "name": "w11-lite",
            "type": "qemu",
            "cpu": 0,
            "template": 0,
            "vmid": 776,
            "status": "stopped",
            "id": "qemu/776",
            "diskread": 0,
            "maxcpu": 4,
            "mem": 0,
            "node": "pve",
            "maxdisk": 0,
            "disk": 0,
            "netin": 0,
            "netout": 0,
            "diskwrite": 0,
            "maxmem": 8589934592
          },
          {
            "netin": 37193019325,
            "maxmem": 8589934592,
            "diskwrite": 351514779136,
            "netout": 15888237103,
            "disk": 0,
            "maxdisk": 107374182400,
            "node": "pve",
            "mem": 7138874128,
            "maxcpu": 6,
            "tags": "windo",
            "diskread": 165750811136,
            "vmid": 777,
            "template": 0,
            "id": "qemu/777",
            "status": "running",
            "type": "qemu",
            "cpu": 0.0101253237076607,
            "uptime": 3638760,
            "name": "w10rdp"
          },
          {
            "maxmem": 8589934592,
            "netout": 0,
            "diskwrite": 0,
            "netin": 0,
            "disk": 0,
            "maxdisk": 0,
            "node": "pve",
            "mem": 0,
            "maxcpu": 4,
            "diskread": 0,
            "id": "qemu/778",
            "status": "stopped",
            "vmid": 778,
            "template": 0,
            "cpu": 0,
            "type": "qemu",
            "uptime": 0,
            "name": "w10-2025-05-uefi"
          },
          {
            "mem": 298270841,
            "maxcpu": 1,
            "diskread": 92852026,
            "netin": 5306512362,
            "maxmem": 1073741824,
            "diskwrite": 3377819648,
            "netout": 35679429,
            "maxdisk": 21474836480,
            "disk": 0,
            "node": "pve",
            "uptime": 3638755,
            "name": "TS-810",
            "vmid": 781,
            "template": 0,
            "id": "qemu/781",
            "status": "running",
            "type": "qemu",
            "cpu": 0.0274363610143064
          },
          {
            "cpu": 0.006369155235464,
            "type": "qemu",
            "id": "qemu/782",
            "status": "running",
            "vmid": 782,
            "template": 0,
            "uptime": 3638750,
            "name": "haos",
            "disk": 0,
            "maxdisk": 34359738368,
            "node": "pve",
            "maxmem": 4294967296,
            "netout": 784594054,
            "diskwrite": 38758294528,
            "netin": 12653545164,
            "diskread": 2202897920,
            "tags": "proxmox-helper-scripts",
            "mem": 3924680704,
            "maxcpu": 2
          },
          {
            "diskread": 641868452,
            "maxcpu": 2,
            "mem": 1547031809,
            "node": "pve",
            "disk": 0,
            "maxdisk": 34359738368,
            "netin": 7835475,
            "diskwrite": 441203200,
            "netout": 46836,
            "maxmem": 2147483648,
            "uptime": 4144,
            "name": "WinXP",
            "type": "qemu",
            "cpu": 0.506102873710331,
            "vmid": 799,
            "template": 0,
            "status": "running",
            "id": "qemu/799"
          }
        ]
      }
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Method: POST, Url: https://192.168.10.122:8006/api2/json/nodes/pve/qemu/733/spiceproxy
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      Parameters:
      proxy : 192.168.10.122
dbug: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      StatusCode:          InternalServerError
      ReasonPhrase:        Configuration file 'nodes/pve/qemu-server/733.conf' does not exist
      IsSuccessStatusCode: False
trce: Corsinvest.ProxmoxVE.Api.PveClientBase[0]
      {
        "data": null
      }
Error: Configuration file 'nodes/pve/qemu-server/733.conf' does not exist
</details>

**Comment by franklupo** [comment]
Could you attach the formatted log files?

best regards

**Comment by Sniper013220** [comment]
[log.txt](https://github.com/user-attachments/files/15715041/log.txt)

**Comment by franklupo** [comment]
new version available

**Comment by Sniper013220** [comment]
Thanks
