### ISSUE TITLE
Problem Connetion

### ISSUE THREAD

**Issue by feelancer21** [Corsinvest/cv4pve-pepper#5]
I am using the tool with Ubuntu 20.04.

`/opt/cv4pve-pepper/cv4pve-pepper --host=192.168.2.5 --username=root@pam --password=root123 --vmid=101 --viewer /usr/bin/remote-viewer 
`
I get always the error "Problem connection!". What's wrong?
I started it with --debug too. But where is the log?

Regards Steffen

**Comment by sakharovaan** [comment]
@steff123 maybe you need to specify the port, like `192.168.2.5:8006 `?
