### ISSUE TITLE
Cannot connect if node firewall is on

### ISSUE THREAD

**Issue by Silent-Hunter** [Corsinvest/cv4pve-pepper#7]
It says Error: unknown host x.x.x.x

If I set the node's firewall to No, it works fine. What firewall exceptions do I need to make?

**Comment by franklupo** [comment]
The spice in Proxmox VE web work?

**Comment by Silent-Hunter** [comment]
Yes it does, works fine. I'm just not sure what to put in the node's firewall to allow things outside of the web management to access it.
-------- Original Message --------

**Comment by franklupo** [comment]
What settings have you put in the firewall?

**Comment by Silent-Hunter** [comment]
I've tried a few. I tried putting just an IP range of 192.168.0.2-192.168.0.255, I've tried putting just port 8006, TCP and UDP. I'm not sure what to put under the network interface though. Maybe I'm getting that wrong. I didn't think I would need to make a firewall exception at all, since I assumed this program used the same management interface as the rest of Proxmox.
-------- Original Message --------

**Comment by franklupo** [comment]
test new relase with parameter --proxy

**Comment by franklupo** [comment]
Test new version. I imporve the log. Use the parameter --debug and attach me result. 

Bets regards

**Comment by Silent-Hunter** [comment]
Apologies, was unable to access my computer for a while. For some reason, the versioon I was using now works. The new one does not.

It opens Spice, but then Spice just says: `Unable to connect to the graphic server C:\Users\Silent\AppData\Local\Temp\tmp7427.vv`

But since the old one works now, I'm not sure there's any issue anymore.

**Comment by franklupo** [comment]
Hi,
use parameter --proxy

**Comment by Silent-Hunter** [comment]
Okay, it doesn't work with --proxy. I wasn't sure what to put for the proxy IP so I put the same one as --host. Old version still seems to be working, even though it wasn't before.

cv4pve-pepper.exe --host=192.168.0.X:8006 --api-token user@pam!user=token --vmid 101 --viewer "C:\Program Files\VirtViewer v9.0-256\bin\remote-viewer.exe" --proxy 192.168.0.X --debug
Error: unknown host 192.168.0.X
Problem connection!
================ EXCEPTION ================
System.ApplicationException
Problem connection!
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.CommandOptionExtension.ClientTryLogin(CommandLineApplication command)
   at Corsinvest.ProxmoxVE.Pepper.Program.<>c__DisplayClass0_0.<Main>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

**Comment by franklupo** [comment]
The error is
Error: unknown host 192.168.0.X

**Comment by Silent-Hunter** [comment]
Yeah, the new version can't see the host no matter what. The old one started working, with a firewall rule.
